### ISSUE TITLE
Crouching Introduces perspective Bug When Turning Head

### ISSUE THREAD

**Issue by sassi006** [Nibre/MotherVR#183]
So I downloaded this MOD and everything was going super well... until I reached a part where I needed to crouch. After crouching and then uncrouching I felt something was off and started to feel pretty motion sick. I ran some tests, and I can confirm that there is some sort of a bug triggered by crouching that messes with how the game translates your head movements in game. Basically, rotating your head to the left results in your perspective shifting a centimeter or two to the right and visa versa.  Quitting to menu and then returning to the game fixes it, but then it's back as soon as you crouch. It's also very noticeable when using snap turn. Rather than having clean turns, it kind of bounces around a bit before settling.

**Comment by Battou2501** [comment]
Same here. After crouching perspective gets messed up.

**Comment by LazySlavik** [comment]
Can confirm, that happens to me also, to put it simple: camera starts rotating around the center of your eyes instead of around the neck

**Comment by JanSob** [comment]
Yes, I have the same issue. I fixed it by resetting the view, just two clicks on the gamepad.

**Comment by hundenmarvin** [comment]
I have this problem to. But resetting the view or quitting to menu didn´t solve it like it did for some of you. Any suggestions?

**Comment by JanSob** [comment]
> I have this problem to. But resetting the view or quitting to menu didn´t solve it like it did for some of you. Any suggestions?

Apparently this was introduced with the 'newest' version. It should be fixed if you go back one version (Beta 0.6?)

**Comment by hundenmarvin** [comment]
> Apparently this was introduced with the 'newest' version. It should be fixed if you go back one version (Beta 0.6?)

Ah, I see. But iirc the older version had another tracking problem where you were unable to lean your head backwards? I will have to pick between 2 different tracking problems I guess.

**Comment by wulf21** [comment]
Thx for pointing this out. I was wondering, why I had no problems when I started the game, but as soon as I was in the station through a vent, I got motion sick pretty quickly (I normally don't get motion sick at all, even in games that have scenes where you get flung through the air).

Well then, I guess I will have to open/close menu everytime after uncrouching.

**Comment by Dozer58** [comment]
I'm using version 0.6 (which fixes the crouch button problem) 
The perspective shift when turning head after crouching is on that version as well, re-centering or going to menu doesn't fix it so game is unplayable for me :(
Using Rift CV1 and Xbox one controller with wireless adapter.

**Comment by Brusura** [comment]
I can confirm the bug while crouching or entering a vent shaft , going to menu or resetting view does nothing, only thing that fix it is reloading, my spec:

Version 0.8.1 of MotherVR
Oculus Quest 2 + Virtual Desktop
SteamVR 1.15.16
Alien Isolation ( Epic Store )

**Comment by EricJanss** [comment]
Same here, it's the only thing holding me back for a playthrough

**Comment by hectorC** [comment]
I just tried this otherwise great VR mod for AI and I got the same problem. Right after emerging from the first time you go through an airlock the pivot point of the head rotation is off center and produces perspective translation shifts when rotating.

**Comment by hectorC** [comment]
This issue indeed makes it unplayable due to it being a motion sickness inducer. I couldn't find a way of fixing it other than restarting the game, which considering the number of times you have to crouch or go through vents makes it not practical.
